# Welcome to Jekyll!
#

# Site settings
title: Luis P Perez
email: luispe at gmail
description: >-
  Technologist passionate for creating products that customers love. Dad, foodie, traveler, stock trader.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luispe.me" # the base hostname & protocol for your site

# Social Media Settings
github_username:  luispic2021
github_organization: CodeAndCandlesticks
linkedin_url: https://www.linkedin.com/in/luispic/

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
